### ISSUE TITLE
Website changes

### ISSUE THREAD

**Issue by Arunish** [CommunityLogiq/urbanlogiq.com#11]
Need to fix the button for the box on the right

![pasted image at 2017_08_21 06_48 pm](https://user-images.githubusercontent.com/31229349/29545445-35dc88e8-86a3-11e7-9cd7-f7a11105bf61.png)

**Comment by Arunish** [comment]
https://www.urbanlogiq.com/economic

Transportation is spelled incorrectly

![pasted image at 2017_08_21 06_49 pm](https://user-images.githubusercontent.com/31229349/29545498-80c4f890-86a3-11e7-8547-ba8a832e1058.png)

**Comment by Arunish** [comment]
https://www.urbanlogiq.com/planning

the font for the line "Track the progress.... " looks out of place.

**Comment by Arunish** [comment]
https://www.urbanlogiq.com/resources

On the resources page, the solutions and company breadcrums are dimmed -- I'm not sure if that's supposed to change as we go to different pages, just something I noticed

**Comment by Arunish** [comment]
https://www.urbanlogiq.com/platform 

The bottom panel on each page shows the word "Platform" and "Solution" - however, there are no hyperlinks associated with the words.

**Comment by punjab** [comment]
@Arunish One issue per ticket please.

**Comment by bopeng48** [comment]
all fixed
