### ISSUE TITLE
Report not generating volume graph

### ISSUE THREAD

**Issue by Arunish** [CommunityLogiq/urbanlogiq.com#19]
Report is for intersection: Intersection of 152 ST & 84 AVE
For the dates: 2016-11-01 and 2017-07-02

![image](https://user-images.githubusercontent.com/31229349/29640344-6477b77e-8813-11e7-9a20-fc15a0e0f786.png)

**Comment by bopeng48** [comment]
@Arunish , it's not this repo. Could you put this on trello? Jen will deal with it
