### ISSUE TITLE
Refactor Website Code

### ISSUE THREAD

**Issue by uldeployer** [CommunityLogiq/urbanlogiq.com#21]
Hey @bopeng48 

This morning I had to make a fix for Leah and realized our website code is all over. This is not going to cut it and is not maintainable code. Create a new branch and please do the following:

1. Make sure there are following _include files
- head.html
- header.html
- nav.html
- js_files.html
- footer.html

2. I want absolutely no head code repeated in any layout file. They should all have just `include head.html` markup. Absolutely no exceptions!

3. Remove all commented CSS code.

4. Remove every piece of inline CSS. Move it to appropriate css classes.

5. Make all CSS files .scss
So instead of writing 

```
// article.css
article.blog-post ul {
  text-align: left;
}

article.blog-post ul li {
  color: #2199e8;
}
```

you should be writing this:

```
// article.scss
article.blog-post ul {
  text-align: left;
  li {
    color: #2199e8;
  }
}
```

6. All main wrappers using seperate CSS file, should have same name as the css file. E.g. if team page is only page using team.css, make sure your markup has following wrapper around the whole content:

```
<div class="team">

</div>
```

And all code within `team.scss` page should be subclassed within .team

```
// team.scss
.team{
  h2{
    margin: 0px;
  }
  p{
    color: #ccc;
  }
}
```

Please refactor this code and get back to me when done. 

7. Fix any JS errors and `console.log` statements that are showing up on console

Get @jenyeeiam's help if need be.

**Comment by bopeng48** [comment]
Refactor done by @jenyeeiam
