### ISSUE TITLE
Add a custom ul/li css tag for sharing buttons

### ISSUE THREAD

**Issue by punjab** [CommunityLogiq/urbanlogiq.com#22]
1. Center buttons
2. Remove bullets
<img width="304" alt="screen shot 2017-08-28 at 3 35 26 pm" src="https://user-images.githubusercontent.com/1588699/29796610-f2567c50-8c06-11e7-896e-832f7e7a7443.png">

**Comment by bopeng48** [comment]
refactor done by @jenyeeiam
