### ISSUE TITLE
Social media share preview image of www.urbanlogiq.com

### ISSUE THREAD

**Issue by hchandi** [CommunityLogiq/urbanlogiq.com#23]
Currently, the fetched preview on social media sites, when sharing our website, shows 500 Startups logo

**Comment by punjab** [comment]
Fixed.
![screen shot 2017-08-29 at 7 20 46 pm](https://user-images.githubusercontent.com/1588699/29852506-4e1deaa8-8cef-11e7-9887-29a9b86d6b6b.png)
